apiVersion: v1
kind: Pod
metadata:
  name: chris-db
spec:
  containers:
      envFrom:
        - configMapRef:
            name: secrets
      image: docker.io/library/postgres:13
      name: chris-db
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: chris-db-data
  restartPolicy: OnFailure
  volumes:
    - name: chris-db-data
      persistentVolumeClaim:
        claimName: chris-db-data
volumes:
  - name: chris-db
    hostPath:
      path: /var/lib/containers/storage/volumes/chris-db
