name: Validate Podman Pod YAML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: validate podman pod yaml
      uses: instrumenta/kubeval-action@master
      with:
        files: development-pod.yaml