
name: Validate Podman Pod YAML

on:
  push:
    branches:    
      - '*' # testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3